version: '2'

services:
  scaffold:
    image: huygensing/scaffold:buildbase
    build: 
      dockerfile: Dockerfile.buildbase
      context: .
    environment:
      - jsApp_prefix=/
      - debug_server=true
    ports:
      - "8080:8080"
      - "3001:3001"
      - "8082:8082"
      - "5858:5858"
    volumes: 
      - .:/app
